apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: <namespace>
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 8081
  - name: metrics
    port: 9113
    targetPort: 9113