apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: <namespace>
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      containers:
      - name: fiks-nginx-openshift
        image: ghcr.io/ks-no/openshift-nginx/fiks-nginx-openshift:1.9.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args:
          - "-nginx.scrape-uri=http://localhost:8081/nginx_status"
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
          - containerPort: 9113
            name: metrics
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config